# Generated by Django 3.1.6 on 2021-02-23 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_auto_20210220_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['number'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 11, 34, 48, 826245)),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
