# Generated by Django 3.1.6 on 2021-03-02 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0006_auto_20210225_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 11, 40, 15, 258347)),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
