# Generated by Django 3.1.6 on 2021-03-02 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0007_auto_20210302_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 22, 19, 28, 179006)),
        ),
    ]
