# Generated by Django 3.1.7 on 2021-03-17 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0008_auto_20210302_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Completed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 17, 46, 33, 725861)),
        ),
    ]
