# Generated by Django 3.1.7 on 2021-03-17 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0009_auto_20210317_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Completed',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 17, 47, 18, 271754)),
        ),
    ]
